"""
Financial term glossary  - definitions and hover-tooltip helper.

tt(text, key=None) wraps any financial term in a <span> that shows
a definition popup on hover.  Requires the .fin-term CSS class to be
injected into the page (done once in app/main.py).
"""

_OER_TIP = (
    "Operating Expense Ratio (OER)  - What percentage of revenue goes "
    "to operating costs. Lower is better. "
    "Benchmark: 35%–55%. Formula: Operating Expenses ÷ Total Revenue"
)
_DSCR_TIP = (
    "Debt Service Coverage Ratio (DSCR)  - How many times NOI covers "
    "the annual loan payment. Below 1.0x means the property can't cover "
    "its debt. Benchmark: 1.25x or higher. "
    "Formula: NOI ÷ Annual Debt Service"
)
_PAYROLL_TIP = (
    "Payroll % of Revenue  - Staff wages and benefits as a share of Total Revenue. "
    "Typically the largest controllable expense. Benchmark: 10%–25%."
)
_MGMT_TIP = (
    "Management Fee %  - Property management fees as a share of Total Revenue. "
    "Benchmark: 4%–8% for professional management."
)
_CTRL_TIP = (
    "Controllable % of Total OpEx  - Share of operating expenses that "
    "management can directly influence. Useful for benchmarking efficiency."
)

GLOSSARY: dict = {
    # ── Core P&L figures ──────────────────────────────────────────────────────
    "TOTAL_REVENUE": {
        "tip": (
            "Total Revenue  - All income generated by the property: "
            "rental income, fees, and other tenant charges. "
            "The top line of the income statement."
        )
    },
    "OPERATING_EXPENSES": {
        "tip": (
            "Operating Expenses  - Day-to-day costs to run the property: "
            "payroll, utilities, taxes, insurance, and management fees. "
            "Does not include debt service (loan payments)."
        )
    },
    "NOI": {
        "tip": (
            "Net Operating Income (NOI)  - Total Revenue minus Operating Expenses. "
            "The primary measure of a property's profitability before debt payments. "
            "Formula: Revenue - Operating Expenses"
        )
    },
    "NET_INCOME": {
        "tip": (
            "Net Income  - What remains after ALL expenses including debt service. "
            "Lower than NOI because loan payments and other non-operating items are deducted."
        )
    },
    "CASH_FLOW": {
        "tip": (
            "Cash Flow  - Actual cash available after all expenses, debt service, "
            "and balance sheet changes (prepaid items, escrow, reserves). "
            "Can differ significantly from Net Income even when profitable."
        )
    },

    # ── Revenue line items ─────────────────────────────────────────────────────
    "GROSS_POTENTIAL_RENT": {
        "tip": (
            "Gross Potential Rent (GPR)  - Maximum possible rent if every unit "
            "were occupied at market rate. The starting point for revenue calculations."
        )
    },
    "VACANCY_LOSS": {
        "tip": (
            "Vacancy Loss  - Revenue lost because units are unoccupied. "
            "Expressed as a percentage of Gross Potential Rent. "
            "Industry benchmark: below 7%."
        )
    },
    "CONCESSION_LOSS": {
        "tip": (
            "Concession Loss  - Revenue given away as incentives to attract or "
            "retain tenants, such as free rent months or move-in specials."
        )
    },
    "NET_RENTAL_REVENUE": {
        "tip": (
            "Net Rental Revenue  - Gross Potential Rent minus Vacancy, Concessions, "
            "and Bad Debt. Represents the rental income actually collected."
        )
    },

    # ── Expense line items ─────────────────────────────────────────────────────
    "DEBT_SERVICE": {
        "tip": (
            "Debt Service  - Loan payments including both principal and interest. "
            "Subtracted from NOI to reach Net Income. "
            "Used to calculate the Debt Service Coverage Ratio (DSCR)."
        )
    },
    "CONTROLLABLE_EXPENSES": {
        "tip": (
            "Controllable Expenses  - Costs management can directly influence, "
            "such as payroll, repairs, and marketing. "
            "Contrast with non-controllable expenses like taxes and insurance."
        )
    },
    "NON_CONTROLLABLE_EXPENSES": {
        "tip": (
            "Non-Controllable Expenses  - Fixed or externally-set costs that "
            "management cannot easily change, such as real estate taxes, "
            "insurance premiums, and loan payments."
        )
    },

    # ── Financial ratios (keyed by ratio_calculator.py name field) ────────────
    "OER":                      {"tip": _OER_TIP},
    "OPERATING_EXPENSE_RATIO":  {"tip": _OER_TIP},
    "NOI_MARGIN": {
        "tip": (
            "NOI Margin  - Net Operating Income as a percentage of Total Revenue. "
            "Higher is better. Benchmark: 40%–65%. "
            "Formula: NOI ÷ Total Revenue"
        )
    },
    "VACANCY_RATE": {
        "tip": (
            "Vacancy Rate  - Percentage of potential rent lost to empty units. "
            "Lower is better. Benchmark: below 7%. "
            "Formula: Vacancy Loss ÷ Gross Potential Rent"
        )
    },
    "DSCR":                         {"tip": _DSCR_TIP},
    "DEBT_SERVICE_COVERAGE_RATIO":  {"tip": _DSCR_TIP},
    "CONCESSION_RATE": {
        "tip": (
            "Concession Rate  - Total concessions as a percentage of Gross Potential "
            "Rent. High rates may signal difficulty filling units. Benchmark: below 2%."
        )
    },
    "BAD_DEBT_RATE": {
        "tip": (
            "Bad Debt Rate  - Uncollected rent as a percentage of revenue. "
            "High bad debt indicates tenant payment problems. Benchmark: below 1%."
        )
    },
    "PAYROLL_PCT":              {"tip": _PAYROLL_TIP},
    "PAYROLL_%_OF_REVENUE":     {"tip": _PAYROLL_TIP},
    "MGMT_FEE_PCT":             {"tip": _MGMT_TIP},
    "MGMT_FEE_%_OF_REVENUE":    {"tip": _MGMT_TIP},
    "CONTROLLABLE_PCT":                 {"tip": _CTRL_TIP},
    "CONTROLLABLE_%_OF_TOTAL_OPEX":     {"tip": _CTRL_TIP},
    "BREAK_EVEN_OCCUPANCY": {
        "tip": (
            "Break-Even Occupancy  - Minimum occupancy rate needed to cover all "
            "operating expenses. Below this point the property loses money. "
            "Formula: Operating Expenses ÷ Gross Potential Rent"
        )
    },
    "CASH_FLOW_MARGIN": {
        "tip": (
            "Cash Flow Margin  - Actual cash generated as a percentage of revenue "
            "after all expenses, debt, and balance sheet changes. "
            "Formula: Cash Flow ÷ Total Revenue"
        )
    },
}


def tt(text: str, key: str = None) -> str:
    """
    Return HTML that wraps *text* in a hover tooltip showing its definition.
    Falls back to plain text if the term is not in the glossary.

    key   - explicit GLOSSARY lookup key (optional).  If omitted the key is
            derived from *text* by upper-casing and normalising separators.
    """
    raw = key if key is not None else text
    # Normalise: uppercase, spaces→underscores, remove parens
    lookup = (
        raw.upper()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("/", "_")
        .replace("(", "")
        .replace(")", "")
        .strip("_")
    )
    entry = GLOSSARY.get(lookup) or GLOSSARY.get(lookup.replace("PCT", "%"))
    if not entry or not entry.get("tip"):
        return text
    tip = entry["tip"].replace('"', "&quot;").replace("'", "&#39;")
    return f'<span class="fin-term" data-tip="{tip}">{text}</span>'
